# Generated by Django 4.2.14 on 2024-09-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('riven', models.CharField(max_length=75, verbose_name='Рівень')),
                ('stupin', models.CharField(max_length=75, verbose_name='Ступінь')),
                ('galuz', models.CharField(max_length=75, verbose_name='Галузь знань')),
                ('specialnist', models.CharField(max_length=75, verbose_name='Спеціальність')),
                ('specializaciya', models.CharField(max_length=75, verbose_name='Спеціалізація')),
                ('osvKvalifikaciya', models.CharField(max_length=150, verbose_name='Освітня кваліфікація')),
                ('profKvalifikaciya', models.CharField(max_length=150, verbose_name='Професійна кваліфікація')),
            ],
        ),
        migrations.CreateModel(
            name='FormaKontrolus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Форма контролю')),
            ],
        ),
        migrations.CreateModel(
            name='KomponentEducationalPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodND', models.CharField(max_length=32, verbose_name='Назва')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('kredutu', models.PositiveIntegerField(default=1)),
                ('semestr', models.PositiveIntegerField(default=1)),
                ('educationalProgram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_programs.educationalprograms')),
                ('formaKontrolu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_programs.formakontrolus')),
            ],
        ),
    ]
