# Generated by Django 4.2.14 on 2024-09-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenteducationalprograms',
            name='kodND',
            field=models.CharField(max_length=32, verbose_name='Код н/д'),
        ),
    ]
