# Generated by Django 4.2.14 on 2024-10-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_programs', '0002_alter_komponenteducationalprograms_kodnd'),
        ('group', '0001_initial'),
        ('vukladach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobochiyNavchalnuyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_programs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_programs.educationalprograms')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.groups')),
            ],
        ),
        migrations.CreateModel(
            name='ElementRNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kredutuECTS1sm', models.PositiveIntegerField()),
                ('Godun', models.PositiveIntegerField()),
                ('Godun1sm', models.PositiveIntegerField()),
                ('lekcii1sm', models.PositiveIntegerField()),
                ('praktuchni1sm', models.PositiveIntegerField()),
                ('laboratorni1sm', models.PositiveIntegerField()),
                ('samostiynaRobota1sm', models.PositiveIntegerField()),
                ('Godun2sm', models.PositiveIntegerField()),
                ('lekcii2sm', models.PositiveIntegerField()),
                ('praktuchni2sm', models.PositiveIntegerField()),
                ('laboratorni2sm', models.PositiveIntegerField()),
                ('samostiynaRobota2sm', models.PositiveIntegerField()),
                ('formaKontrolu1sm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementrnp_forma1', to='educational_programs.formakontrolus')),
                ('formaKontrolu2sm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementrnp_forma2', to='educational_programs.formakontrolus')),
                ('robochiyNavchalnuyPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robochiy_navchalnuy_plan.robochiynavchalnuyplan')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_programs.komponenteducationalprograms')),
                ('vukladach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vukladach.vukladach')),
            ],
        ),
    ]
