# Generated by Django 4.2.14 on 2024-10-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robochiy_navchalnuy_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementrnp',
            name='kredutuECTS2sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='Godun',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='Godun1sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='Godun2sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='kredutuECTS1sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='laboratorni1sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='laboratorni2sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='lekcii1sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='lekcii2sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='praktuchni1sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='praktuchni2sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='samostiynaRobota1sm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='samostiynaRobota2sm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
