# Generated by Django 4.2.14 on 2024-10-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_programs', '0002_alter_komponenteducationalprograms_kodnd'),
        ('robochiy_navchalnuy_plan', '0002_elementrnp_kredutuects2sm_alter_elementrnp_godun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementrnp',
            name='formaKontrolu1sm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elementrnp_forma1', to='educational_programs.formakontrolus'),
        ),
        migrations.AlterField(
            model_name='elementrnp',
            name='formaKontrolu2sm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elementrnp_forma2', to='educational_programs.formakontrolus'),
        ),
    ]
