# Generated by Django 4.2.14 on 2024-12-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafikNavchannya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teoretuchne_navchannya_1sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Теоретичне навчання(1 семестр)')),
                ('praktuka_1sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Практика(1 семестр)')),
                ('sesiya_1sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Зимова сесія')),
                ('kanikylu_1sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Канікули(1 семестр)')),
                ('teoretuchne_navchannya_2sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Теоретичне навчання(2 семестр)')),
                ('praktuka_2sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Практика(2 семестр)')),
                ('sesiya_2sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Літня сесія')),
                ('kanikylu_2sm', models.CharField(blank=True, max_length=75, null=True, verbose_name='Канікули(2 семестр)')),
                ('pidgotovkaKR', models.CharField(blank=True, max_length=75, null=True, verbose_name='Підготовка КР')),
                ('ekzamenaciyna_komisiya', models.CharField(blank=True, max_length=75, null=True, verbose_name='ЕК')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.groups')),
            ],
        ),
    ]
