# Generated by Django 4.2.14 on 2024-12-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('educational_programs', '0002_alter_komponenteducationalprograms_kodnd'),
        ('control', '0008_remove_komponenteducationalprograms_educationalprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Den',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('dzvinok', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Rozklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rozklad.den')),
                ('facultet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.facultys')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.groups')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rozklad.para')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_programs.komponenteducationalprograms')),
            ],
        ),
    ]
