# Generated by Django 4.2.14 on 2024-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('adres', models.CharField(max_length=150, verbose_name='Адреса факультету')),
                ('dean', models.CharField(max_length=50, verbose_name='Декан Факультету')),
            ],
        ),
    ]
