# Generated by Django 4.2.14 on 2024-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_kafedras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedras',
            name='adresKafedra',
            field=models.CharField(max_length=150, verbose_name='Адреса кафедри'),
        ),
        migrations.AlterField(
            model_name='kafedras',
            name='managerKafedra',
            field=models.CharField(max_length=50, verbose_name='Завідувач кафедри'),
        ),
    ]
