# Generated by Django 4.2.14 on 2024-09-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_educationalprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaKontrolus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Форма контролю')),
            ],
        ),
        migrations.CreateModel(
            name='KomponentEducationalPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodND', models.CharField(max_length=32, verbose_name='Назва')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('kredutu', models.IntegerField(verbose_name='Кількість кредитів')),
                ('semestr', models.IntegerField(verbose_name='Семестр')),
                ('educationalProgram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.educationalprograms')),
                ('formaKontrolu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.formakontrolus')),
            ],
        ),
    ]
