# Generated by Django 4.2.14 on 2024-09-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_komponenteducationalprograms_kredutu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komponenteducationalprograms',
            name='educationalProgram',
        ),
        migrations.RemoveField(
            model_name='komponenteducationalprograms',
            name='formaKontrolu',
        ),
        migrations.DeleteModel(
            name='EducationalPrograms',
        ),
        migrations.DeleteModel(
            name='FormaKontrolus',
        ),
        migrations.DeleteModel(
            name='KomponentEducationalPrograms',
        ),
    ]
