# Generated by Django 4.2.14 on 2024-12-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_remove_komponenteducationalprograms_educationalprogram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultys',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
    ]
