# Generated by Django 4.2.14 on 2024-10-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0008_remove_komponenteducationalprograms_educationalprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vukladach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya', models.CharField(max_length=75, verbose_name="Ім'я")),
                ('prizvusche', models.CharField(max_length=75, verbose_name='Прізвище')),
                ('poBatkovi', models.CharField(max_length=75, verbose_name='По батькові')),
                ('posada', models.CharField(max_length=175, verbose_name='Посада')),
                ('naukovaStupin', models.CharField(max_length=75, verbose_name='Наукова ступінь')),
                ('vcheneZvannya', models.CharField(max_length=75, verbose_name='Вчене звання')),
                ('facultet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.facultys')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.kafedras')),
            ],
        ),
    ]
